name: tmmfast
channels:
  - conda-forge
  - vsc
  - defaults
dependencies:
  - appdirs=1.4.4=pyh9f0ad1d_0
  - brotli=1.0.9=hcfcfb64_8
  - brotli-bin=1.0.9=hcfcfb64_8
  - brotlipy=0.7.0=py38h91455d4_1005
  - ca-certificates=2022.12.7=h5b45459_0
  - certifi=2022.12.7=pyhd8ed1ab_0
  - cffi=1.15.1=py38h57701bc_3
  - charset-normalizer=2.1.1=pyhd8ed1ab_0
  - cryptography=39.0.0=py38h086c683_0
  - cycler=0.11.0=pyhd8ed1ab_0
  - fonttools=4.38.0=py38h91455d4_1
  - freetype=2.12.1=h546665d_1
  - idna=3.4=pyhd8ed1ab_0
  - intel-openmp=2023.0.0=h57928b3_25922
  - jpeg=9e=h8ffe710_2
  - kiwisolver=1.4.4=py38hb1fd069_1
  - lcms2=2.14=ha5c8aab_1
  - lerc=4.0.0=h63175ca_0
  - libblas=3.9.0=16_win64_mkl
  - libbrotlicommon=1.0.9=hcfcfb64_8
  - libbrotlidec=1.0.9=hcfcfb64_8
  - libbrotlienc=1.0.9=hcfcfb64_8
  - libcblas=3.9.0=16_win64_mkl
  - libdeflate=1.17=hcfcfb64_0
  - libhwloc=2.8.0=h039e092_1
  - libiconv=1.17=h8ffe710_0
  - libjpeg-turbo=2.1.4=hcfcfb64_0
  - liblapack=3.9.0=16_win64_mkl
  - libpng=1.6.39=h19919ed_0
  - libsqlite=3.39.4=hcfcfb64_0
  - libtiff=4.5.0=hf8721a0_2
  - libwebp-base=1.2.4=h8ffe710_0
  - libxcb=1.13=hcd874cb_1004
  - libxml2=2.10.3=hc3477c8_0
  - libzlib=1.2.13=hcfcfb64_4
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - matplotlib-base=3.6.3=py38h528a6c7_0
  - mkl=2022.1.0=h6a75c08_874
  - msys2-conda-epoch=20160418=1
  - munkres=1.1.4=pyh9f0ad1d_0
  - openjpeg=2.5.0=ha2aaf27_2
  - openssl=1.1.1s=hcfcfb64_1
  - pandas=1.5.3=py38h5846ac1_0
  - patsy=0.5.3=pyhd8ed1ab_0
  - pip=22.3=pyhd8ed1ab_0
  - pooch=1.6.0=pyhd8ed1ab_0
  - pthread-stubs=0.4=hcd874cb_1001
  - pthreads-win32=2.9.1=hfa6e2cd_3
  - pycparser=2.21=pyhd8ed1ab_0
  - pyopenssl=23.0.0=pyhd8ed1ab_0
  - pyparsing=3.0.9=pyhd8ed1ab_0
  - pysocks=1.7.1=pyh0701188_6
  - python=3.8.0=hc9e8b01_5
  - python-dateutil=2.8.2=pyhd8ed1ab_0
  - python_abi=3.8=2_cp38
  - requests=2.28.2=pyhd8ed1ab_0
  - scipy=1.10.0=py38h0f6ee2a_0
  - seaborn=0.12.2=hd8ed1ab_0
  - seaborn-base=0.12.2=pyhd8ed1ab_0
  - setuptools=65.5.0=pyhd8ed1ab_0
  - six=1.16.0=pyh6c4a22f_0
  - sqlite=3.39.4=hcfcfb64_0
  - statsmodels=0.13.5=py38hbaf524b_2
  - tbb=2021.7.0=h91493d7_1
  - tk=8.6.12=h8ffe710_0
  - typing_extensions=4.4.0=pyha770c72_0
  - ucrt=10.0.22621.0=h57928b3_0
  - unicodedata2=15.0.0=py38h91455d4_0
  - urllib3=1.26.14=pyhd8ed1ab_0
  - vc=14.3=h3d8a991_9
  - vs2015_runtime=14.32.31332=h1d6e394_9
  - wheel=0.37.1=pyhd8ed1ab_0
  - win_inet_pton=1.1.0=pyhd8ed1ab_6
  - xorg-libxau=1.0.9=hcd874cb_0
  - xorg-libxdmcp=1.1.3=hcd874cb_0
  - xz=5.2.6=h8d14728_0
  - zstd=1.5.2=h12be248_6
  - pip:
    - cloudpickle==2.2.0
    - contourpy==1.0.5
    - dask==2022.10.0
    - fsspec==2022.10.0
    - gym==0.26.2
    - gym-notices==0.0.8
    - importlib-metadata==5.0.0
    - locket==1.0.0
    - matplotlib==3.6.1
    - numpy==1.23.4
    - packaging==21.3
    - partd==1.3.0
    - pillow==9.2.0
    - pytz==2022.5
    - pyyaml==6.0
    - tmm-fast==0.1
    - toolz==0.12.0
    - torch==1.12.1
    - zipp==3.10.0
prefix: C:\Users\A.Luce\Anaconda3\envs\tmmfast2
