name: mltf
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - argon2-cffi=20.1.0=py39h2bbff1b_1
  - async_generator=1.10=pyhd3eb1b0_0
  - attrs=21.2.0=pyhd3eb1b0_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - blas=1.0=mkl
  - bleach=3.3.1=pyhd3eb1b0_0
  - bokeh=2.3.3=py39haa95532_0
  - bottleneck=1.3.2=py39h7cc1a96_1
  - ca-certificates=2022.4.26=haa95532_0
  - certifi=2022.5.18.1=py39haa95532_0
  - cffi=1.14.6=py39h2bbff1b_0
  - click=8.0.1=pyhd3eb1b0_0
  - cloudpickle=1.6.0=py_0
  - colorama=0.4.4=pyhd3eb1b0_0
  - cudatoolkit=10.2.89=h74a9793_1
  - cycler=0.10.0=py39haa95532_0
  - cytoolz=0.11.0=py39h2bbff1b_0
  - dask=2021.7.0=pyhd3eb1b0_0
  - dask-core=2021.7.0=pyhd3eb1b0_0
  - decorator=5.0.9=pyhd3eb1b0_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distributed=2021.7.0=py39haa95532_0
  - entrypoints=0.3=py39haa95532_0
  - ffmpeg=4.3.1=ha925a31_0
  - freetype=2.10.4=hd328e21_0
  - fsspec=2021.7.0=pyhd3eb1b0_0
  - future=0.18.2=py39hcbf5309_3
  - gym=0.18.0=py39h832f523_1
  - heapdict=1.0.1=py_0
  - icc_rt=2019.0.0=h0cc432a_1
  - icu=58.2=ha925a31_3
  - importlib-metadata=3.10.0=py39haa95532_0
  - importlib_metadata=3.10.0=hd3eb1b0_0
  - intel-openmp=2021.3.0=haa95532_3372
  - ipykernel=5.3.4=py39h7b7c402_0
  - ipython=7.22.0=py39hd4e2768_0
  - ipython_genutils=0.2.0=pyhd3eb1b0_1
  - jedi=0.17.2=py39haa95532_1
  - jinja2=3.0.1=pyhd3eb1b0_0
  - jpeg=9b=hb83a4c4_2
  - jsonschema=3.2.0=py_2
  - jupyter_client=6.1.12=pyhd3eb1b0_0
  - jupyter_core=4.7.1=py39haa95532_0
  - jupyterlab_pygments=0.1.2=py_0
  - kiwisolver=1.3.1=py39hd77b12b_0
  - libpng=1.6.37=h2a8f88b_0
  - libsodium=1.0.18=h62dcd97_0
  - libtiff=4.2.0=hd0e1b90_0
  - libuv=1.40.0=he774522_0
  - locket=0.2.1=py39haa95532_1
  - lz4-c=1.9.3=h2bbff1b_0
  - m2w64-gcc-libgfortran=5.3.0=6
  - m2w64-gcc-libs=5.3.0=7
  - m2w64-gcc-libs-core=5.3.0=7
  - m2w64-gmp=6.1.0=2
  - m2w64-libwinpthread-git=5.0.0.4634.697f757=2
  - markupsafe=2.0.1=py39h2bbff1b_0
  - matplotlib=3.3.4=py39haa95532_0
  - matplotlib-base=3.3.4=py39h49ac443_0
  - mistune=0.8.4=py39h2bbff1b_1000
  - mkl=2021.3.0=haa95532_524
  - mkl-service=2.4.0=py39h2bbff1b_0
  - mkl_fft=1.3.0=py39h277e83a_2
  - mkl_random=1.2.2=py39hf11a4ad_0
  - msgpack-python=1.0.2=py39h59b6b97_1
  - msys2-conda-epoch=20160418=1
  - nbclient=0.5.3=pyhd3eb1b0_0
  - nbconvert=6.1.0=py39haa95532_0
  - nbformat=5.1.3=pyhd3eb1b0_0
  - nest-asyncio=1.5.1=pyhd3eb1b0_0
  - notebook=6.4.0=py39haa95532_0
  - numexpr=2.7.3=py39hb80d3ca_1
  - numpy=1.20.3=py39ha4e8547_0
  - numpy-base=1.20.3=py39hc2deb75_0
  - olefile=0.46=py_0
  - openssl=1.1.1o=h2bbff1b_0
  - packaging=21.0=pyhd3eb1b0_0
  - pandas=1.3.0=py39hd77b12b_0
  - pandocfilters=1.4.3=py39haa95532_1
  - parso=0.7.0=py_0
  - partd=1.2.0=pyhd3eb1b0_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pillow=8.3.1=py39h4fa10fc_0
  - pip=21.1.3=py39haa95532_0
  - prometheus_client=0.11.0=pyhd3eb1b0_0
  - prompt-toolkit=3.0.17=pyh06a4308_0
  - psutil=5.8.0=py39h2bbff1b_1
  - pycparser=2.20=py_2
  - pyglet=1.5.16=py39hcbf5309_0
  - pygments=2.9.0=pyhd3eb1b0_0
  - pyparsing=2.4.7=pyhd3eb1b0_0
  - pyqt=5.9.2=py39hd77b12b_6
  - pyrsistent=0.18.0=py39h2bbff1b_0
  - python=3.9.5=h6244533_3
  - python-dateutil=2.8.2=pyhd3eb1b0_0
  - python_abi=3.9=2_cp39
  - pytorch=1.10.2=py3.9_cuda10.2_cudnn7_0
  - pytorch-mutex=1.0=cuda
  - pytz=2021.1=pyhd3eb1b0_0
  - pywin32=228=py39he774522_0
  - pywinpty=0.5.7=py39haa95532_0
  - pyyaml=5.4.1=py39h2bbff1b_1
  - pyzmq=20.0.0=py39hd77b12b_1
  - qt=5.9.7=vc14h73c81de_0
  - scipy=1.6.2=py39h66253e8_1
  - seaborn=0.11.1=pyhd3eb1b0_0
  - send2trash=1.5.0=pyhd3eb1b0_1
  - setuptools=52.0.0=py39haa95532_0
  - sip=4.19.13=py39hd77b12b_0
  - six=1.16.0=pyhd3eb1b0_0
  - sortedcontainers=2.4.0=pyhd3eb1b0_0
  - sqlite=3.36.0=h2bbff1b_0
  - tblib=1.7.0=py_0
  - terminado=0.9.4=py39haa95532_0
  - testpath=0.5.0=pyhd3eb1b0_0
  - tk=8.6.10=he774522_0
  - toolz=0.11.1=pyhd3eb1b0_0
  - torchvision=0.11.3=py39_cu102
  - tornado=6.1=py39h2bbff1b_0
  - traitlets=5.0.5=pyhd3eb1b0_0
  - typing_extensions=3.10.0.0=pyh06a4308_0
  - tzdata=2021a=h52ac0ba_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wcwidth=0.2.5=py_0
  - webencodings=0.5.1=py39haa95532_1
  - wheel=0.36.2=pyhd3eb1b0_0
  - wincertstore=0.2=py39h2bbff1b_0
  - winpty=0.4.3=4
  - xz=5.2.5=h62dcd97_0
  - yaml=0.2.5=he774522_0
  - zeromq=4.3.3=ha925a31_3
  - zict=2.0.0=pyhd3eb1b0_0
  - zipp=3.5.0=pyhd3eb1b0_0
  - zlib=1.2.11=h62dcd97_4
  - zstd=1.4.9=h19a0ad4_0
  - pip:
    - tmm==0.1.8
prefix: C:\Users\Username\AppData\Local\Continuum\anaconda3\envs\mltf
